version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}   
      - run:
          name: install dependencies
          command: cd node-test && npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - node_modules   
      - run:
          name: test
          command: npm run test --passWithNoTests
workflows:
  build:
    jobs:
      - build_and_test
